version: '2'

services:
  db:
    environment:
      POSTGRES_DB: app_db
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: changeme
    restart: always
    image: postgres:13.1
    expose:
      - "5432"
  redis:
    restart: always
    image: redis:6.0.10
    expose:
      - "6379"
  elasticsearch:
    image: elasticsearch:6.8.13
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    restart: always
    ports:
      - "9200:9200"
    environment:
      - discovery.type=single-node
  app:
    environment:
      DJANGO_SECRET_KEY: changeme
      DATABASE_URL: postgres://app_user:changeme@db/app_db
      CACHE_URL: redis://redis
      ELASTICSEARCH_ENDPOINT: elasticsearch
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./pfwra:/code/pfwra
    links:
      - db:db
      - redis:redis
      - elasticsearch:elasticsearch
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
      - elasticsearch
