# Generated by Django 3.1.7 on 2021-05-12 04:21

from django.db import migrations, models
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.embeds.blocks
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_grouppage_external_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='grouppage',
            name='facebook_url',
            field=models.URLField(blank=True, help_text='Facebook URL of the group, if any', null=True),
        ),
        migrations.AddField(
            model_name='grouppage',
            name='instagram_url',
            field=models.URLField(blank=True, help_text='Instagram URL of the group, if any', null=True),
        ),
        migrations.AddField(
            model_name='grouppage',
            name='twitter_url',
            field=models.URLField(blank=True, help_text='Twitter URL of the group, if any', null=True),
        ),
        migrations.AlterField(
            model_name='grouppage',
            name='body',
            field=wagtail.core.fields.StreamField([('heading_block', wagtail.core.blocks.StructBlock([('heading_text', wagtail.core.blocks.CharBlock(form_classname='title', required=True)), ('size', wagtail.core.blocks.ChoiceBlock(blank=True, choices=[('', 'Select a header size'), ('h3', 'H3'), ('h4', 'H4'), ('h5', 'H5'), ('h6', 'H6')], required=False))])), ('paragraph_block', wagtail.core.blocks.RichTextBlock(features=['bold', 'italic', 'link', 'ol', 'ul', 'document-link'], icon='fa-paragraph', template='common/blocks/paragraph.html')), ('image_block', wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(required=True)), ('caption', wagtail.core.blocks.CharBlock(required=False)), ('attribution', wagtail.core.blocks.CharBlock(required=False))])), ('block_quote', wagtail.core.blocks.StructBlock([('text', wagtail.core.blocks.TextBlock()), ('attribute_name', wagtail.core.blocks.CharBlock(blank=True, label='e.g. Mary Berry', required=False))])), ('embed_block', wagtail.embeds.blocks.EmbedBlock(help_text='Insert an embed URL e.g https://www.youtube.com/embed/SGJFWirQ3ks', icon='fa-s15', template='common/blocks/embed.html'))], blank=True, verbose_name='Page body'),
        ),
    ]
